apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-postgresql-api.fullname" . }}
  labels:
    {{- include "otus-postgresql-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: web-app
  selector:
    {{- include "otus-postgresql-api.selectorLabels" . | nindent 4 }}
