apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-postgresql-api-ingress
spec:
  #ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otus-postgresql-api
            port:
              number: 9000
