replicaCount: 2
 
image:
  repository: myhardway/otus_microservices_arch_2nd_hw
  tag: latest
  #pullPolicy: Always
  #imagePullPolicy: Always
 
service:
  type: NodePort
  port: 9000
 
postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"


#prometheus:
#  prometheusSpec:
#    serviceMonitorSelectorNilUsesHelmValues: false


prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}


metrics:
  serviceMonitor:
    enabled: true

grafana:
  grafana.ini:
    server:
      domain: arch.homework
      root_url: http://arch.homework/grafana/
      serve_from_sub_path: false

  #ingress:
    ## If true, Grafana Ingress will be created
    ##
    #enabled: true

    ## Annotations for Grafana Ingress
    ##
    #annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    #labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    #hosts:
    #  - arch.homework

    ## Path for grafana ingress
    #path: /grafana-ingress/



#grafana:
#  path: /monitoring/


#postgresql:
#  auth:
#    postgresPassword: xDXLJdLkXf
#  enabled: true
#  postgresqlUsername: bXl1c2Vy
#  postgresqlPassword: cGFzc3dk
#  postgresqlDatabase: bXlhcHA=
#  service:
#    port: "5432"






#serviceAccount:
  # Specifies whether a service account should be created
#  create: true
  # Annotations to add to the service account
#  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
#  name: ""


#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: arch.homework
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


