apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  PORT: {{ .Values.postgresql.service.port | quote }}
  HOST: otus-postgresql-api-0

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  PASSWORD:  {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_NAME:  {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
